spring.config.import=optional:file:.env[.properties]

spring.application.name=ebank
server.port=8081

# mySql
spring.datasource.url=${PROD_URL}
spring.datasource.username=${PROD_USERNAME}
spring.datasource.password=${PROD_PASS}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT Config
jwt.secret.string=${JWT_SECRET}
jwt.expiration.time=${JWT_EXPIRATION_TIME}

# Mail Config
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.host=smtp.gmail.com
spring.mail.port=587

#Enable TLS SMTP MAIL to
# use to encrypt the mails by TLS protocol
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

password.reset.link=http://e-bank-frontend-deploy.s3-website.eu-north-1.amazonaws.com/reset-password?code=


# AWS S3 Config

aws.accessKeyId=${AWS_ACCESS_KEY}
aws.secretAccessKey=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.s3.bucketName=${AWS_BUCKET_NAME}
